name: met_women
channels:
  - conda-forge
  - defaults
dependencies:
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cryptography=44.0.2
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - libcxx=20.1.1
  - libexpat=2.6.4
  - libffi=3.4.2
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - ncurses=6.5
  - oauthlib=3.2.2
  - openssl=3.4.1
  - pip=25.0.1
  - pycparser=2.22
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dotenv=1.0.1
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - tk=8.6.13
  - tweepy=4.15.0
  - tzdata=2025a
  - urllib3=2.3.0
  - zstandard=0.23.0
