name: run tweet.py

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: executing python script
        env:
            consumer: ${{ secrets.CONSUMER }}
            ACCESS_TOKEN_SECRET: ${{ secrets.DQD_ACCESS_TOKEN_SECRET }}
            CONSUMER_KEY: ${{ secrets.DQD_CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.DQD_CONSUMER_SECRET }}
        run: python main.py


