# https://github.com/actions/starter-workflows/blob/main/ci/python-package-conda.yml

name: run tweet.py

on:
  schedule:
    - cron: '0 * * * *' # at top of every hour
#    - cron: '0 0 * * *' # At 00:00 every day
  
  push: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        env:
            API_KEY: ${{ secrets.API_KEY }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            CONSUMER_KEY: ${{ secrets.DQD_CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.DQD_CONSUMER_SECRET }}
        run: |
          conda env update --file environment.yml --name met_women
          python tweet.py


