name: run tweet.py

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run tweet.py
        with:
          consumer: ${{ secrets.consumer }}
	  API_SECRET: ${{ secrets.API_SECRET }}
	  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
	  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      	env:
          API_KEY: ${{ secrets.API_KEY }}
	  API_SECRET: ${{ secrets.API_SECRET }}
	  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
	  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python tweet.py

           
#      - name: execute py script # run tweet.py
#        env:
#          API_KEY: ${{ secrets.API_KEY }}
#	   API_SECRET: ${{ secrets.API_SECRET }}
#	   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#	   ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
#        run: python tweet.py
#          
#      - name: commit files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add -A
#          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
#          
#      - name: push changes
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: main 