name: run tweet.py

on:
  schedule:
    - cron: '10 2 * * *'
#    - cron: '0 0 * * *' # At 00:00 every day

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: executing python script
        env:
            API_KEY: ${{ secrets.API_KEY }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            CONSUMER_KEY: ${{ secrets.DQD_CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.DQD_CONSUMER_SECRET }}
        run: python main.py


